const { configs, helpers, components, WEB_ROLES } = require("./generateJson")
const createConfig = require("./src/createConfig")
const createHelpers = require("./src/createHelpers")
const createConstants = require("./src/createConstants")
const createComponent = require("./src/createComponent")
createConfig(configs)
createHelpers(helpers)
createConstants(components, WEB_ROLES)
createComponent(components)